### /public/user/register
POST localhost:8081/public/register
Content-Type: application/json
{
  "username": "유저명",
  "content": "컨텐츠"
}

###
POST localhost:8081/public/register
###

### /user/logout
POST localhost:8081/users/logout

### /user/current
POST localhost:8081/users/current

### /api/noties
POST localhost:8081/api/notes